#!/bin/bash
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2017-2018
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
#############################################################################

source /var/onap_tests/_test_base
source /var/onap/integration

covered_functions=(
"clone_integration_repos"
)

# test_clone_integration_repos() - Verify that Integration repositories are cloned properly
function test_clone_integration_repos {
    clone_repos "integration"

    asserts_file_exist ${src_folders[integration]}/README.md
    asserts_file_exist ${src_folders[integration]}/devtool/LICENSE
    #asserts_file_exist ${src_folders[integration]}/seccom/
}

if [ "$1" != '*' ]; then
    unset covered_functions
    covered_functions=$1
fi
main "${covered_functions[@]}"
