#!/bin/bash
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2017-2018
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
#############################################################################

source /var/onap/functions

# _build_vvp_images() - Builds VNFSDK images from source code
function _build_vvp_images {
    echo "pass"
}

# get_vvp_images - Function that clones vvp Docker images
function get_vvp_images {
    if [[ "$build_image" == "True" ]]; then
        _build_vvp_images
    else
        pull_docker_image refrepo:1.0-STAGING-latest
        pull_docker_image refrepo:latest
    fi
}

# install_vvp - Function that installs vvp Docker images
function install_vvp {
    echo "pass"
}

# init_vvp() - Init VNFSDK services
function init_vvp {
    if [[ "$clone_repo" == "True" ]]; then
        clone_repos "vvp"
        if [[ "$compile_repo" == "True" ]]; then
            compile_repos "vvp"
        fi
    fi

    if [[ "$skip_get_images" == "False" ]]; then
        get_vvp_images
        if [[ "$skip_install" == "False" ]]; then
            install_vvp
        fi
    fi
}
